// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuuByq2HlhPIfB-U0HqmE08KSj_FYUSQ8',
    appId: '1:677824116708:android:b950cdba9bfade049bf9f1',
    messagingSenderId: '677824116708',
    projectId: 'whatsapp-clone-2497c',
    storageBucket: 'whatsapp-clone-2497c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeipG84btaWudYI8OV5GMlS015vkVXZF4',
    appId: '1:677824116708:ios:381049143282f0109bf9f1',
    messagingSenderId: '677824116708',
    projectId: 'whatsapp-clone-2497c',
    storageBucket: 'whatsapp-clone-2497c.appspot.com',
    androidClientId: '677824116708-2ba7fo377vqtgiv3vcijqjjvb8a3j4ni.apps.googleusercontent.com',
    iosClientId: '677824116708-69j6e8juql7d56cqshfqvkqepok9rtea.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
